//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitapcuoimonweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDienThoaiEntities : DbContext
    {
        public ShopDienThoaiEntities()
            : base("name=ShopDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Tb_ChiTietHD> Tb_ChiTietHD { get; set; }
        public virtual DbSet<Tb_ChiTietPhieuNHap> Tb_ChiTietPhieuNHap { get; set; }
        public virtual DbSet<Tb_ChiTietSanPham> Tb_ChiTietSanPham { get; set; }
        public virtual DbSet<Tb_DanhMucSanPham> Tb_DanhMucSanPham { get; set; }
        public virtual DbSet<Tb_HoaDon> Tb_HoaDon { get; set; }
        public virtual DbSet<Tb_Kho> Tb_Kho { get; set; }
        public virtual DbSet<Tb_NhaCungCap> Tb_NhaCungCap { get; set; }
        public virtual DbSet<Tb_NhanVien> Tb_NhanVien { get; set; }
        public virtual DbSet<Tb_PhieuNhap> Tb_PhieuNhap { get; set; }
        public virtual DbSet<Tb_SanPham> Tb_SanPham { get; set; }
    }
}
