//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitapcuoimonweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ChiTietPhieuNHap
    {
        public long ID { get; set; }
        public Nullable<long> IDPhieuNhap { get; set; }
        public Nullable<long> IdSanPham { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> Thanhtien { get; set; }
    
        public virtual Tb_PhieuNhap Tb_PhieuNhap { get; set; }
        public virtual Tb_SanPham Tb_SanPham { get; set; }
    }
}
