//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitapcuoimonweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ChiTietHD
    {
        public long ID { get; set; }
        public string IdHoaDon { get; set; }
        public Nullable<long> IdSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual Tb_HoaDon Tb_HoaDon { get; set; }
        public virtual Tb_SanPham Tb_SanPham { get; set; }
    }
}
