//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitapcuoimonweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_HoaDon()
        {
            this.Tb_ChiTietHD = new HashSet<Tb_ChiTietHD>();
        }
    
        public string Id { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string SDTKH { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ChiTietHD> Tb_ChiTietHD { get; set; }
    }
}
