//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitapcuoimonweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_SanPham()
        {
            this.Tb_ChiTietHD = new HashSet<Tb_ChiTietHD>();
            this.Tb_ChiTietPhieuNHap = new HashSet<Tb_ChiTietPhieuNHap>();
            this.Tb_ChiTietSanPham = new HashSet<Tb_ChiTietSanPham>();
            this.Tb_Kho = new HashSet<Tb_Kho>();
        }
    
        public long Id { get; set; }
        public Nullable<int> IdDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public string GhiChu { get; set; }
        public string AnhSanPham { get; set; }
        public Nullable<double> GiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ChiTietHD> Tb_ChiTietHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ChiTietPhieuNHap> Tb_ChiTietPhieuNHap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ChiTietSanPham> Tb_ChiTietSanPham { get; set; }
        public virtual Tb_DanhMucSanPham Tb_DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Kho> Tb_Kho { get; set; }
    }
}
